<?xml version="1.0" encoding="UTF-8"?>

<!--引入dtd来约束这个xml -->
<!--文档类型 根标签名字 网络上的dtd dtd的名称    dtd的路径  -->
<!--<!DOCTYPE stus PUBLIC "//UNKNOWM" "unknown.dtd"> -->

<!-- 引入本地的DTD :根标签名字 引入本地的DTD dtd的位置 -->
<!DOCTYPE stus SYSTEM "stus.dtd">

<!-- xml文档里面直接嵌入dtd的约束法则 -->
<!-- <!DOCTYPE stus [
	<!ELEMENT stus (stu)>
	<!ELEMENT stu (name,age)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
]>
 -->
 
<stus>
	<stu id="10086">
		<name>张三</name>
		<age>18</age>
	</stu>
	
	<stu id="10087">
		<name>李四</name>
		<age>18</age>
	</stu>
</stus>